### ISSUE TITLE
Encrypted disk/image support

### ISSUE THREAD

**Issue by dmitry-bakaleinik-sap** [cloudfoundry-incubator/bosh-alicloud-cpi-release#107]
Hello,

According to the documentation in AliCloud, system disk encryption is possible by using encrypted image (https://www.alibabacloud.com/help/doc-detail/110666.htm)

Currently, the AliCloud BOSH CPI supports only data disk encryption and not system disk encryption.

Please add a support for stemcell upload with enabled encryption and KMS (if provided) to make it possible to create instances with encrypted system disk in addition to encrypted data disk.

Terraform example:
https://www.terraform.io/docs/providers/alicloud/r/image_copy.html#encrypted

**Comment by xiaozhu36** [comment]
HI @dmitry-bakaleinik-sap This issue has been fixed by #125  and contained by release 34.0.0. Please have a check.
