### ISSUE TITLE
Configuring slbs stopped working with 32.0.0

### ISSUE THREAD

**Issue by friegger** [cloudfoundry-incubator/bosh-alicloud-cpi-release#119]
With `32.0.0` using load balancer via VM extension does not work anymore. It works fine with `31.0.0`. Potentially this is caused by https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/pull/115 and/or https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/pull/114.

Also see docs https://bosh.io/docs/alicloud-cpi/#resource-pools. The formatting is broken by the way.

**Comment by chushenmeshile** [comment]
@friegger What problems do you encounter with 32.0.0 and why do you think 114 or 115 pr has problems

**Comment by shaoyongfeng** [comment]
Hi ,
following is a very simple code to reproduce this issue
vm_extensions:
- name: landscape_credhub_lb
  cloud_properties:
    slbs:
    - (( .terraform.credhub_lb_id ))
- name: landscape_uaa_lb
  cloud_properties:
    slbs:
    - (( .terraform.uaa_lb_id ))
The lb_ids are the output from terraform of a alicloud_slb resource:
output "credhub_lb_id" {
  value = alicloud_slb.credhub-lb.id
}

**Comment by chushenmeshile** [comment]
What are the errors you encountered during deployment

**Comment by shaoyongfeng** [comment]
![image](https://user-images.githubusercontent.com/41664705/103334515-95069900-4aac-11eb-80b2-dc34f13a01cf.png)
the symptom is VM is not attached to LB as above

**Comment by chushenmeshile** [comment]
I'm sorry, I can't see the image content information, but I think it may be a parameter type conversion error. Maybe you need to convert the parameter type from string to int.

**Comment by shaoyongfeng** [comment]
Hi @chushenmeshile ，
I don't understand what you mean. This issue only happens in new cpi version. there should be some changes in CPI which causes this issue. Do you try to reproduce it？

**Comment by chushenmeshile** [comment]
The parameter type has changed from string to int, and the default value has been cancelled. Therefore, I think there may be a problem with the data type you passed in the configuration file.

**Comment by xiaozhu36** [comment]
HI @friegger I am sorry for the late reply. This issue has been fixed by #120 and it has been published in the release v33.0.0. Please have a check.
