### ISSUE TITLE
Use Linux type 'Other' instead of 'Ubuntu' for Ubuntu Bionic

### ISSUE THREAD

**Issue by StefanWutz** [cloudfoundry-incubator/bosh-alicloud-cpi-release#122]
Uploading an Ubuntu Bionic stemcell will lead to changed kernel boot parameters on alicloud for Ubuntu Bionic images. For example, the kernel boot parameter `ipv6.disable=1` will be removed.

As discussed with alicloud team we will change the Linux type from 'Ubuntu' to 'Other' so that the original kernel boot parameters will remain.
Related to https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/132

/cc @xiaozhu36

**Comment by xiaozhu36** [comment]
HI @StefanWutz This issue has been fixed by #124 and contained by release 34.0.0. Please have a check.
