### ISSUE TITLE
BoshEnv struct does not have Blobstores field in registry/agent_settings.go

### ISSUE THREAD

**Issue by yatzek** [cloudfoundry-incubator/bosh-alicloud-cpi-release#132]
BoshEnv struct in [registry/agent_settings.go](https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/blob/a6ac88749c52a8735c09252c37dcc9718fc67f36/src/bosh-alicloud-cpi/registry/agent_settings.go#L84) is generally out of sync with bosh agent settings:

https://github.com/cloudfoundry/bosh-agent/blob/master/settings/settings.go#L276

The missing "Blobstores" field, in particular, is an issue with regard to [signed blobstore urls](https://bosh.io/docs/director-blobstore-signed-urls/) feature.
Blobstore details from bosh env are not passed to IaaS registry user-data and this results in a broken bosh agent configuration. 

The issue we are seeing is that the bosh agent tries to fetch blobs from a blobstore using signed urls (https) without a blobstore ca certificate:
```
Get "https://10.0.3.11:25250/signed/ba/cc5de529-b202-47c9-576a-4747d217e649?e=86400&st=xzH6ojhFStSiN2P7GSgljCrA3eGyMuDNjoBZZ_1_hxQ&ts=1623772918": x509: certificate signed by unknown authority
```

**Comment by StefanWutz** [comment]
@xiaozhu36: What is your opinion on that?

**Comment by yatzek** [comment]
@xiaozhu36: Would it make sense to keep agent Env settings generic like in the GCP cpi: https://github.com/cloudfoundry/bosh-google-cpi-release/blob/a0893932f636403e5524f8d5f4055257a75e2637/src/bosh-google-cpi/registry/agent_settings.go#L71
?

This way when new fields are added in the future, things will just come through.

**Comment by yatzek** [comment]
@xiaozhu36: are you guys planning a new release any time soon?

**Comment by xiaozhu36** [comment]
Hi @yatzek The release 39.0.0 has been published. Please have a check.
