### ISSUE TITLE
Unable to use latest bosh version - registry job has been removed

### ISSUE THREAD

**Issue by ionphractal** [cloudfoundry-incubator/bosh-alicloud-cpi-release#153]
In bosh-deployment [v272.0.0](https://github.com/cloudfoundry/bosh/releases/tag/v272.0.0) the registry job has been removed completely.

The alicloud cpi seems to require the registry job, hence we're stuck to [v271.20.0](https://github.com/cloudfoundry/bosh/releases/tag/v271.20.0) which is the latest version with the registry job available.

Is it planned to remove the registry requirement for alicloud cpi? If so, can you already have a schedule?

**Comment by benjaminguttmann-avtq** [comment]
@xiaozhu36 anything you can do about this one?

**Comment by ionphractal** [comment]
@friegger We've updated to bosh v272.6.0 with cpi v45 now and everything works fine. Thank you!
