### ISSUE TITLE
Deploy vm failure due cpi errors

### ISSUE THREAD

**Issue by ninja-at-work** [cloudfoundry-incubator/bosh-alicloud-cpi-release#29]
Hi all,

I'm receiving errors related to CPI api requests during component deployment.
The errors are following:
- Status Code: 400 Code: IncompleteSignature Message: The request signature does not conform to Aliyun standards. server string to sign is
- IllegalTimestamp Message: The input parameter "Timestamp" that is mandatory for processing this request is not supplied.' in 'create_vm' CPI method - /var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/cloud/external_cpi.rb:196:in `handle_error'

**Comment by ninja-at-work** [comment]
The request signature does not conform to Aliyun standards. server string to sign is - this message indicates bad credentials.

**Comment by lordcf** [comment]
Hi,
I'm getting this error,

Status Code: 400 Code: IllegalTimestamp Message: The input parameter "Timestamp" that is mandatory for processing this request is not supplied.' in 'create_vm' CPI method.

Please let me know if u have faced & resolved the issue too.

**Comment by imbolo** [comment]
@ninja-at-work @lordcf 
I met the same problem. In my case, it is caused by the wrong date setting of bosh-director.
You can run command `date` to check it.
![image](https://user-images.githubusercontent.com/3530602/39418860-58e0ce5a-4c8f-11e8-9f68-05cbfd32acf2.png)
