### ISSUE TITLE
`bosh create-env` fails on Mac due to `bosh-alicloud-cpi/packaging` script setting GOROOT

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry-incubator/bosh-alicloud-cpi-release#36]
I believe the following lines may not be necessary:

https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/blob/dcd22b97b48eb2569fd74994a92d6d9226853537/packages/bosh-alicloud-cpi/packaging#L13-L16

Especially given the `golang/packaging` script says that if you're on Mac, you need to install Golang yourself:

https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/blob/dcd22b97b48eb2569fd74994a92d6d9226853537/packages/golang/packaging#L17-L20

Those lines assume my `$GOROOT` is `/usr/local/go` which is not the case since I installed Golang with Homebrew, which I suspect is quite common for most Mac users with Golang.  I deleted the 4 lines, create a dev release, and was then able to proceed.

**Comment by xiaozhu36** [comment]
Hi @Amit-PivotalLabs Thanks for your suggestion and I will update them.
