### ISSUE TITLE
Bosh CPI communicate with IaaS apis over http and not via https

### ISSUE THREAD

**Issue by alexwo** [cloudfoundry-incubator/bosh-alicloud-cpi-release#49]
The default configured in the alibaba cloud-sdk-go library set all communication to work with http.
https://github.com/aliyun/alibaba-cloud-sdk-go/issues/85

Please review the below [PR](https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/pull/48) that changes the BOSH CPI default to use https instead.

**Comment by xiaozhu36** [comment]
Fixed
