### ISSUE TITLE
Bosh CPI does not support uploading of full stemcells from bosh.io

### ISSUE THREAD

**Issue by alexwo** [cloudfoundry-incubator/bosh-alicloud-cpi-release#51]
The bosh.io published stemcells can't be uploaded and used by bosh cpi.

Please review below PR suggestions with potential fix for this issue:
https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/pull/50

**Comment by benjaminguttmann-avtq** [comment]
For me it is still not working. Tried it with `bosh-stemcell-170.12-alicloud-kvm-ubuntu-xenial-go_agent` from bosh.io

**Comment by alexwo** [comment]
1.Please make sure you have configured bosh deployment with security_token="" if you don't using that as a method to authenticate.

Sample config with security_token="" :
```
bosh create-env bosh-deployment/bosh.yml \
 --state=state.json \
 --vars-store=creds.yml \
 -o bosh-deployment/alicloud/cpi.yml \
 -o bosh-deployment/jumpbox-user.yml \
 -v director_name=my-bosh \
 -v internal_cidr=192.168.0.0/24 \
 -v internal_gw=192.168.0.1 \
 -v internal_ip=192.168.0.7 \
 -v vswitch_id=... \
 -v security_group_id=... \
 -v access_key_id=... \
 -v access_key_secret=... \
 -v region=cn-beijing \
 -v zone=cn-beijing-e
 -v key_pair_name=... \
 -v private_key=bosh.pem
 -v security_token=""
```

2.In order to for the bosh deployment to upload stemcells, you should  to enable access from your ECS service account to the buckets. https://www.alibabacloud.com/help/doc-detail/25464.htm

**Comment by benjaminguttmann-avtq** [comment]
Thanks for the detailed information, I'll check on this and let you know the result... but one additional question, to which bucket do I need to have access because at the moment I use the internal blobstore of the BOSH director to save the stemcells ? So is it trying to save the stemcell in a bucket?

**Comment by alexwo** [comment]
That should be alright..
Bosh CPI will try to create a bucket using the CPI in AliCloud and delete it afterwords.

**Comment by beyhan** [comment]
Does it mean that I have to configure the BOSH Directore with an AliCloud blobstore, when I use stemcells from bosh.io?

**Comment by alexwo** [comment]
Hi @beyhan,
The bosh director does not need require any special configuration about the AliCloud blob storage.
The only requirement is that the bosh director API user will have access to AliCloud blob storage.

**Comment by xiaozhu36** [comment]
Fixed by release v20.
