### ISSUE TITLE
CPI cannot handle "prepaid" ECS instances

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [cloudfoundry-incubator/bosh-alicloud-cpi-release#56]
Hi,

at the moment it is possible to configure the cloud-config in such a way that so-called `subscription` instances get created but it is not possible to stop these instances again via the CPI. At the moment it is necessary to transform subscription VMs into 'pay-as-you-go' instances manually via the GUI before they can be deleted. Maybe it is possible to add an automation for this to the CPI.

Thank you.

**Comment by xiaozhu36** [comment]
@benjaminguttmann-avtq The CPI has supported to create 'PrePaid' Ecs instance by setting `charge_type = "PrePaid"`, `charge_period` and `charge_period_unit `. Please check it.

**Comment by benjaminguttmann-avtq** [comment]
Hi @xiaozhu36 , my issue was not about not being able to create those instances. That was working fine for me, but I had problems stopping those PrePaid instances via the CPI. But if that is fixed now I am fine with closing it.
