### ISSUE TITLE
BOSH CPI does not support HTTP Proxy

### ISSUE THREAD

**Issue by thoHeinze** [cloudfoundry-incubator/bosh-alicloud-cpi-release#65]
We try to use the Alicloud BOSH CPI in a setup together with a HTTP Proxy, which is support by other CPI like Openstack: https://bosh.io/jobs/openstack_cpi?source=github.com/cloudfoundry/bosh-openstack-cpi-release&version=42#p%3denv

Based on our tests it seems that the Alicloud CPI / a bosh director with this CPI does not support setting any http proxy to connect to the Cloud API. Can you please add support for this?

**Comment by cloudyday** [comment]
Is there something happening on this one?

**Comment by xiaozhu36** [comment]
HI @cloudyday @thoHeinze The release [22](https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/releases/tag/v22) has supported http proxy. Please check it.

**Comment by xiaozhu36** [comment]
Closed by no reply
