### ISSUE TITLE
Command "delete-deployment" doesn't delete all relevant vms

### ISSUE THREAD

**Issue by ala2208** [cloudfoundry-incubator/bosh-alicloud-cpi-release#71]
Hi,

I run delete-deployment command and not all relevant vms were deleted.
Some of VMs are in "stopped" status while status of "delete-deployment" is Succeeded.

Expected behaviour:
All relevant VMs deleted.

**Comment by xiaozhu36** [comment]
HI @ala2208 Can you share me the deployment manifest? and help me to reoccur it.

**Comment by ala2208** [comment]
Hi,

The issue is not reproduced with the latest version v22.

**Comment by xiaozhu36** [comment]
@ala2208 Thanks for your feedback. Please reopen when this issue reproduced.
