### ISSUE TITLE
Command "delete-deployment" doesn't delete PostgreSQL instance

### ISSUE THREAD

**Issue by ala2208** [cloudfoundry-incubator/bosh-alicloud-cpi-release#72]
Hi,

I run delete-deployment command and PostgreSQL 10.0 instance was not deleted when status of the command was "Succeeded".

Expected behaviour:
PostgreSQL instance deleted.

Thanks,
Ala

**Comment by xiaozhu36** [comment]
HI @ala2208 Can you show me your deployment manifest?

**Comment by ala2208** [comment]
Hi,

The issue is not reproduced with the latest version v22.

**Comment by xiaozhu36** [comment]
@ala2208 Thanks for your feedback. Please reopen it when this issue reproduced.
