### ISSUE TITLE
Inconsistent versioning of releases

### ISSUE THREAD

**Issue by s4heid** [cloudfoundry-incubator/bosh-alicloud-cpi-release#73]
The formats of the published release tags are inconsistent. Some releases are tagged with lower `v` prefix, some have a capital `V`, and there is also one which has `release` as prefix.

Unfortunately, the inconsistent use of tags confuses the concourse [github-release-resource](https://github.com/concourse/github-release-resource), which breaks our automation pipelines. It would be nice if the versioning would follow a certain pattern.

**Comment by xiaozhu36** [comment]
HI @s4heid I am sorry for this incosistent and I also found this issue when I build myself pipeline. The next releases will be  tagged with lower `v` prefix.

**Comment by s4heid** [comment]
Thanks a lot @xiaozhu36, I’m going to close this issue.
