### ISSUE TITLE
detach disk failed: [SDK.TimeoutError] The request timed out 6 times

### ISSUE THREAD

**Issue by OlegGerber** [cloudfoundry-incubator/bosh-alicloud-cpi-release#76]
CPI Release Version: v22

Task 1717 | 11:26:52 | Updating instance kafka: kafka/161030c1-4dee-4440-9f92-a25d18ae8d1f (1) (00:01:27)
                    L Error: CPI error 'Bosh::Clouds::CloudError' with message 'input=`{"method": "detach_disk","arguments": ["i-uf69zwlpzq62ucuaw6u0","d-uf6b8z1fqaq4uqdt0cca"],"context": {"director_uuid": "966dffcd-b901-409d-813f-85a5caf8b392","request_id": "cpi-818263","vm": {"stemcell": {"api_version": 2}}},"api_version": 1}` detach disk d-uf6b8z1fqaq4uqdt0cca from i-uf69zwlpzq62ucuaw6u0 failed: [SDK.TimeoutError] The request timed out 6 times(6 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout.
caused by:
Post https://ecs-cn-hangzhou.aliyuncs.com/?AccessKeyId=LTAIcUMNoUit2SfO&Action=DetachDisk&DiskId=d-uf6b8z1fqaq4uqdt0cca&Format=JSON&InstanceId=i-uf69zwlpzq62ucuaw6u0&RegionId=cn-shanghai&SecurityToken=&Signature=WA74bljVcMX%2BkX7WhnsSh%2FfMUR4%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=4665f240c75b49c6b799b0eda2d313fb&SignatureType=&SignatureVersion=1.0&Timestamp=2019-05-21T11%3A28%3A14Z&Version=2014-05-26: dial tcp 140.205.155.65:443: i/o timeout' in 'detach_disk' CPI method (CPI request ID: 'cpi-818263')
Task 1717 | 11:28:19 | Updating deployment:
  Expected task '1717' to succeed but state is 'error'

**Comment by xiaozhu36** [comment]
HI @OlegGerber Do you set ECS endpoint by cpi properties or environment `ECS_ENDPOINT` manually?

**Comment by OlegGerber** [comment]
Hi @xiaozhu36 ,
We did not set manually the "ECS_ENDPOINT" properties but use the default provided values.

**Comment by xiaozhu36** [comment]
HI @OlegGerber What is your ` default provided values`?

**Comment by OlegGerber** [comment]
Hi @xiaozhu36 ,
I sent you the director.yml  via email

**Comment by xiaozhu36** [comment]
Hi @OlegGerber It seems like the director does not set ecs endpoint. You region is `cn-shanghai` and its endpoint is `ecs-cn-hangzhou.aliyuncs.com`, that is correct. So, I think the issue maybe from you director can not access public network. Can you ping the endpoint `ecs-cn-hangzhou.aliyuncs.com` in your director?

**Comment by OlegGerber** [comment]
Hi @xiaozhu36 ,
See the result:
bosh/eff5a049-8745-4b38-a575-e26205e9fd50:~$ nslookup ecs-cn-hangzhou.aliyuncs.com
Server:		100.100.2.136
Address:	100.100.2.136#53

ecs-cn-hangzhou.aliyuncs.com	canonical name = popunify-public.aliyuncs.com.
popunify-public.aliyuncs.com	canonical name = popunify-public.aliyuncs.com.gds.alibabadns.com.
Name:	popunify-public.aliyuncs.com.gds.alibabadns.com
Address: 106.11.172.2


bosh/eff5a049-8745-4b38-a575-e26205e9fd50:~$ curl ifconfig.io
47.91.93.212

**Comment by xiaozhu36** [comment]
HI @OlegGerber This issue came from network connection failed leads deleting vm failed. I will push the product team to accelerate the specified request domain to avoid the network connection.

**Comment by xiaozhu36** [comment]
HI @OlegGerber We have configured global acceleration service for the endpoint `ecs-cn-hangzhou.aliyuncs.com` and it will avoid the connection timeout error when you access China mainland region service. Please check it.

**Comment by xiaozhu36** [comment]
Fixed and closed by no reply.
