### ISSUE TITLE
Move to semver for versions

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bosh-alicloud-cpi-release#78]
Currently the final release versions are only singular numbers (16, 17, 18). Could we move to semver to indicate the magnitude of feature changes?

**Comment by xiaozhu36** [comment]
Hi @drnic Thanks for your advise. From the v23.0.0, the release will be semver.

**Comment by drnic** [comment]
Thanks. See #79 - can the final releases please be included in the git repo? v23.0.0 missing from https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/tree/master/releases/bosh-alicloud-cpi
