### ISSUE TITLE
Releases 19-22 missing from releases/ folder

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bosh-alicloud-cpi-release#79]
This project only contains releases up to 18, but 19 is referenced in [1], and 22 is the latest github release [2]

* [1] https://github.com/aliyun/bosh-deployment/blob/master/alicloud/cpi.yml#L6-L9
* [2] https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/releases

Could the missing releases please be committed to the git repo? Thanks! xoxo

**Comment by xiaozhu36** [comment]
Hi @drnic , the latest bosh cpi release and light stemcell has been updated in the bosh-deployment. Please check it.
