### ISSUE TITLE
Support CPI API v2

### ISSUE THREAD

**Issue by friegger** [cloudfoundry-incubator/bosh-alicloud-cpi-release#85]
Currently the AliCloud CPI only supports CPI API v1, but v2 is available and many CPIs already support it. Main benefit is, that the Registry becomes obsolete. You can checkout https://bosh.io/docs/v2-migration-guide/ to get an overview of all necessary changes.

**Comment by xiaozhu36** [comment]
HI. @friegger I am sorry for late reply. The latest release v38.0.0 has supported it and please have check.
Please reopen it and let me know if there is any issue.
